VERSION=0.2.0
PROJROOT=/home/jeffmc/dnsbridge
GOPATH=/home/jeffmc/dnsbridge/dnsbridge

build:
	        go install crunchy.com/dnsbridge
	        go install crunchy.com/dnsbridge/dnsbridgeserver
	        go install crunchy.com/dnsbridge/dnsbridgeclient

