VERSION=0.2.0
PROJROOT=$(HOME)/dnsbridge
GOPATH=$(HOME)/dnsbridge

build:
		go install crunchy.com/dnsbridge
		go install crunchy.com/dnsbridge/dnsbridgeserver
		go install crunchy.com/dnsbridge/dnsbridgeclient



